"""
Retrieval service — vector embedding similarity search for Q&A (RAG).

Uses cosine similarity against stored chunk embeddings generated by Gemini
text-embedding-004 during the analysis pipeline.

Falls back to keyword scoring for chunks that pre-date embedding generation.
"""

import logging
import math
import re
from typing import Dict, List

from google.cloud.firestore import Client

from app.services.ai_service import get_embedding

logger = logging.getLogger(__name__)

CASES = "cases"
CHUNKS_SUB = "chunks"


def _cosine_similarity(vec_a: List[float], vec_b: List[float]) -> float:
    """Compute cosine similarity between two vectors."""
    if not vec_a or not vec_b or len(vec_a) != len(vec_b):
        return 0.0
    dot = sum(a * b for a, b in zip(vec_a, vec_b))
    mag_a = math.sqrt(sum(a * a for a in vec_a))
    mag_b = math.sqrt(sum(b * b for b in vec_b))
    if mag_a == 0 or mag_b == 0:
        return 0.0
    return dot / (mag_a * mag_b)


def _keyword_score(text: str, query_words: set) -> float:
    """Fallback keyword overlap score (0..1 normalised)."""
    if not query_words:
        return 0.0
    text_lower = text.lower()
    hits = sum(1 for w in query_words if w in text_lower)
    return hits / len(query_words)


# Common English stop words to strip from keyword fallback
_STOP_WORDS = {
    "the", "a", "an", "is", "in", "of", "and", "to", "my",
    "what", "how", "does", "i", "me", "we", "it", "at", "be",
    "was", "are", "for", "on", "with", "this", "that", "by",
}


def retrieve(
    db: Client, case_id: str, query: str, max_results: int = 8
) -> List[Dict]:
    """
    Retrieve the most relevant document chunks for a given query.

    Strategy:
    1. Embed the query using Gemini text-embedding-004.
    2. For each stored chunk that has an 'embedding' field, compute
       cosine similarity against the query embedding.
    3. For legacy chunks without embeddings, fall back to keyword overlap.
    4. Return top-N results sorted by similarity score descending.
    """
    # Load all chunks for the case
    docs = (
        db.collection(CASES).document(case_id).collection(CHUNKS_SUB).stream()
    )
    chunks = [{"id": d.id, **d.to_dict()} for d in docs]

    if not chunks:
        return []

    # Embed the query
    try:
        query_embedding = get_embedding(query)
    except Exception as e:
        logger.warning("Failed to embed query, using keyword fallback: %s", e)
        query_embedding = []

    # Keyword fallback prep
    query_words = set(re.findall(r"\b\w+\b", query.lower())) - _STOP_WORDS

    scored: List[tuple] = []
    for chunk in chunks:
        chunk_embedding = chunk.get("embedding", [])
        text = chunk.get("text", "")

        if chunk_embedding and query_embedding:
            score = _cosine_similarity(query_embedding, chunk_embedding)
        else:
            # Fallback to keyword scoring for chunks without embeddings
            score = _keyword_score(text, query_words)

        if score > 0:
            scored.append((score, chunk))

    # Sort by score descending
    scored.sort(key=lambda x: x[0], reverse=True)
    return [chunk for _, chunk in scored[:max_results]]
